name: Build RP2 (Pico) with LVGL 8.3

on:
  workflow_dispatch:  # 手动触发
  push:
    branches: [ main ]
    paths:
      - 'ports/rp2/**'
      - 'lib/lv_bindings/**'
      - 'micropython/**'
      - '.github/workflows/rp2_lvgl83_build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 修复：确保子模块被正确拉取
      - name: Checkout lv_micropython (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # 必须：递归拉取子模块（包括LVGL）
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            python3 \
            python3-pip \
            gcc-arm-none-eabi \
            libnewlib-arm-none-eabi \
            libstdc++-arm-none-eabi-newlib
          pip3 install --upgrade pip
          pip3 install pyelftools

      # 现在可以正常进入LVGL目录了
      - name: Set LVGL to 8.3
        run: |
          cd lib/lv_bindings/lvgl
          git checkout v8.3.9  # 切换到8.3版本

      - name: Build RP2 Firmware
        run: |
          cd ports/rp2
          make -j$(nproc) BOARD=pico \
            USER_C_MODULES=../../lib/lv_bindings.cmake \
            LVGL_CONFIG_FILE=../../lib/lv_bindings/lvgl/lv_conf.h

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: rp2-lvgl83-firmware
          path: ports/rp2/build-pico/firmware.uf2
          retention-days: 30